#name of workflow
name: CI
# event that trigger teh workflow
on: []

# define the job and runner
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo hello, world!
          echo add other actions to build,
          echo test, and deploy your project.

