

name: setup_cml

on:
  pull_request:
    branches: [ "main" ]
    
permissions: write-all

jobs:
  train_and_report_eval_performance:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"
        
    - name: set up the cml
      uses: iterative/setup-cml@v1
      
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Pull data
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: dvc pull
      
    - name: Run DVC pipeline
      run: dvc repro
    - name: run cml report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        #print metrics pf current branch
        dvc metrics show --md >> report.md
        # compare metrics with main branch
        # git fetch --prune
        # dvc metrics diff --md main >> report.md
        # create CML report
        cml comment create report.md

      
